steps:
  - label: "Eland :python: {{ matrix.python }} :elasticsearch: {{ matrix.stack }}"
    agents:
      provider: "gcp"
    env:
      PYTHON_VERSION: "{{ matrix.python }}"
      PANDAS_VERSION: '1.5.0'
      TEST_SUITE: "xpack"
      ELASTICSEARCH_VERSION: "{{ matrix.stack }}"
    matrix:
      setup:
        python:
          - '3.10'
          - '3.9'
          - '3.8'
        stack:
          - '8.7-SNAPSHOT'
          - '8.8-SNAPSHOT'
    command: ./.buildkite/run-tests
