steps:
  - label: ":terminal: Lint code"
    env:
      PYTHON_VERSION: 3
    agents:
      provider: "gcp"
      machineType: "n2-standard-2"
    commands:
      - ./.buildkite/lint-code.sh
  - label: ":books: Build documentation"
    env:
      PYTHON_VERSION: 3.9-bookworm
    agents:
      provider: "gcp"
      machineType: "n2-standard-2"
    commands:
      - ./.buildkite/build-documentation.sh
  - label: ":docker: Build Wolfi image"
    env:
      PYTHON_VERSION: 3.11-bookworm
    agents:
      provider: "gcp"
      machineType: "n2-standard-2"
    commands:
      - ./.buildkite/build-docker-images.sh
  - label: ":python: {{ matrix.python }} :elasticsearch: {{ matrix.stack }} :pandas: {{ matrix.pandas }}"
    agents:
      provider: "gcp"
      machineType: "n2-standard-4"
    env:
      PYTHON_VERSION: "{{ matrix.python }}"
      PANDAS_VERSION: "{{ matrix.pandas }}"
      TEST_SUITE: "xpack"
      ELASTICSEARCH_VERSION: "{{ matrix.stack }}"
    matrix:
      setup:
        # Python and pandas versions need to be added to the nox configuration too
        # (in the decorators of the test method in noxfile.py)
        pandas:
          - '1.5.0'
          - '2.2.3'
        python:
          - '3.12'
          - '3.11'
          - '3.10'
          - '3.9'
        stack:          
          - '9.0.0-SNAPSHOT'
    command: ./.buildkite/run-tests
