steps:
  - label: ":terminal: Lint code"
    env:
      PYTHON_VERSION: 3
    agents:
      provider: "gcp"
      machineType: "n2-standard-2"
    commands:
      - ./.buildkite/lint-code.sh
  - label: ":books: Build documentation"
    env:
      PYTHON_VERSION: 3.9-bookworm
    agents:
      provider: "gcp"
      machineType: "n2-standard-2"
    commands:
      - ./.buildkite/build-documentation.sh
  - label: ":docker: Build docker image {{ matrix.platform }}"
    env:
      PYTHON_VERSION: 3.11-bookworm
    agents:
      provider: "gcp"
      machineType: "n2-standard-2"
    commands:
      - ./.buildkite/build-docker-images.sh
  - label: "Eland :python: {{ matrix.python }} :elasticsearch: {{ matrix.stack }}"
    agents:
      provider: "gcp"
      machineType: "n2-standard-4"
    env:
      PYTHON_VERSION: "{{ matrix.python }}"
      PANDAS_VERSION: '1.5.0'
      TEST_SUITE: "xpack"
      ELASTICSEARCH_VERSION: "{{ matrix.stack }}"
    matrix:
      setup:
        python:
          - '3.11'
          - '3.10'
          - '3.9'
          - '3.8'
        stack:          
          - '8.16.0-SNAPSHOT'
          - '8.15.2'
          - '8.14.1'
    command: ./.buildkite/run-tests
